---
title: "Estimating a Bayesian VAR"
author: "Jörg Rieger"
date: "17 7 2019"
output: rmarkdown::html_vignette

vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

# Introduction

The purpose of this vignette is to show how to estimate Bayesian Vector Autoregressive Models using the package bvar2.


We do this by using a

The model is estimated in 2 steps:

* Define the prior for the model
* Estimate the bayesian VAR-model using the abov defined prior

# Setting up the prior

In the first step, we set up the prior. For the simplest case we use an uninformative prior.

While the uninformative prior itself has (as the name says) no prior information about the parameters we aim to estimate. We still have to provide the crator function with some information about the model. These information are

* The number of lags of the model
* Whether the model has an intercept or not

In addition, we have to provide the data to estimate the parameters. The function extracts some basic information from it.

```{r setting prior, echo=TRUE,message=FALSE}
library(bvar2)
data("USMonPol")
prior <-set_prior_uninformative(mydata = USMonPol,nolags = 6, intercept = TRUE)
```
