#' @export
#' @title forecast error variance decomposition for bayesian VARs
#' @param obj S3 object generated by bvar
#' @param h forecast horizon
#' @param id_obj S3 object containing information about identifying the VAR model
#' @param type Type of forecast error variance decomposition. If type = "general" the generalized forecast error variance decomposition is used. For any other values the standard method. While the generalized fevd doesn't use an indefication method to identify structural shocks in the VAR model, this is not true for the standard method. Hence for the generalized fevd there is no need to supply the function via id_obj. If id_obj is not null, there will be a warning message but will still proceed.
#' @param ... currently not used
fevd.bvar <- function(obj,h=12,id_obj=NULL,type="general",...){
  if(type == "general" && !is.null(id_obj)){
    message("Iignoring identification method for generalized forecast error variance decomposition.\n")
  }

  Alpha <- obj$mcmc_draws$Alpha
  Sigma <- obj$mcmc_draws$Sigma
  nreps <- dim(Alpha)[3]
  nVar  <- dim(Alpha)[2]
  intercept <- obj$general_info$intercept
  nolags <- obj$general_info$nolags

  fevd_return <- array(0,dim=c(nVar,nVar,1,nreps))

  if(type == "general"){

    for(ii in 1:nreps){

      current_Alpha <- Alpha[,,ii]
      current_Sigma <- Sigma[,,ii]

      # If the model has an intercept, remove the first row
      if(intercept){

        current_Alpha <- current_Alpha[-c(1),]

      }
      varcoef <- array(0,dim=c(nVar,nVar,nolags))
      for(jj in 1:nolags){

        varcoef[,,jj] <- current_Alpha[((jj-1) * nVar + 1):(jj*nVar),]

      }

      # transform VAR-coefficients into its Moving-Average representation
      vmacoef <- var2vma(varcoef,h,nolags,nVar)

      # Calculate the generalized fevd
      deltatemp <- array(0,dim=c(nVar,nVar))
      for(i in 1:nVar){

        ei <- array(0,dim=c(nVar))
        ei[i] <- 1
        tsum2 <- 0

        for(hh in 1:h){

          tmp <- t(ei) %*% vmacoef[,,hh] %*% current_Sigma[,] %*% t(vmacoef[,,hh]) %*% ei
          tsum2 <- tsum2 + tmp

        }
        for(j in 1:nVar){

          ej <- array(0, dim=c(nVar))
          ej[j] <- 1
          tsum <- 0

          for(hh in 1:h){

            tmp <- (ei %*% vmacoef[,,hh] %*% ej)^2
            tsum <- tsum + tmp

          }

          deltatemp[i,j] <- current_Sigma[i,i]^(-1)*tsum/tsum2

        }
      }

      fevd_return[,,1,ii] <- deltatemp
    }
  }
  else{

    stop("Currently only generalized Forecast Error Variance Decomposition is implemented")

  }


  retlist = structure(list(fevd = fevd_return,noregimes = 1),class="bvfevd")
  return(retlist)
}
